### ISSUE TITLE
[BUG] onMessageReceived throwing NPE

### ISSUE THREAD

**Issue by pizerg** [Azure/azure-notificationhubs-android#286]
**Describe the bug**
NPE exception is sometimes thrown when onMessageReceived is invoked. The error was captured a couple of times via Crashlytics so cannot provide the exact state of the device at the time but mostly sure app was in background and got a push notification.

***Exception or Stack Trace***
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.microsoft.windowsazure.messaging.notificationhubs.NotificationListener.onPushNotificationReceived(android.content.Context, com.google.firebase.messaging.RemoteMessage)' on a null object reference
       at com.microsoft.windowsazure.messaging.notificationhubs.FirebaseReceiver.onMessageReceived(FirebaseReceiver.java:52)
       at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(FirebaseMessagingService.java:235)
       at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(FirebaseMessagingService.java:185)
       at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(FirebaseMessagingService.java:172)
       at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(FirebaseMessagingService.java:161)
       at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$com-google-firebase-messaging-EnhancedIntentService(EnhancedIntentService.java:78)
       at com.google.firebase.messaging.EnhancedIntentService$$ExternalSyntheticLambda0.run(:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.1.0:2)
       at java.lang.Thread.run(Thread.java:920)
```

**To Reproduce**

Configure and register with valid credentials + TAG(s)
Receive a push notification (most likely with app on the background / killed)

***Code Snippet***
During main activity onCreate method:

```
NotificationHub.setListener(NotificationDisplayer())

NotificationHub.start(
    this.application,
    BuildConfig.NOTIFICATION_HUB_NAME,
    BuildConfig.NOTIFICATION_HUB_CS
)
```

NotificationDisplayer just set the channels, etc to be able to show the notification.

And once the user is signed in the following is invoked:

`NotificationHub.addTag("[TAG_HERE]")`

**Expected behavior**
No exceptions are thrown and events are handled seamlessly.

**Setup (please complete the following information):**
 - OS: Android 12
 - Version of the Library used: 1.1.6

**Information Checklist**
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by Klewerro** [comment]
I have very similar or even the same issue.
After starting the application, I'm waiting several seconds to authenticate user (check token using MSAL), then I'm calling:
```Kotlin
NotificationHub.start(
            this.application,
            hubName,
            connectionString
        )
        NotificationHub.clearTags()
        NotificationHub.addTag(userId)
        NotificationHub.setListener(notificationViewModel)
```
Expection found in Firebase logs:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void d8.q.b(android.content.Context, s7.m)' on a null object reference
       at com.microsoft.windowsazure.messaging.notificationhubs.FirebaseReceiver.onMessageReceived(FirebaseReceiver.java:52)
       at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(com.google.firebase:firebase-messaging@@21.0.1:13)
       at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(com.google.firebase:firebase-messaging@@21.0.1:8)
       at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(com.google.firebase:firebase-messaging@@21.0.1:3)
       at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(com.google.firebase:firebase-messaging@@21.0.1:3)
       at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(EnhancedIntentService.java:11)
       at com.google.firebase.messaging.EnhancedIntentService$$Lambda$0.run(com.google.firebase:firebase-messaging@@21.0.1:11)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.android.gms.common.util.concurrent.zza.run(zza.java:6)
       at java.lang.Thread.run(Thread.java:1012)
```
Mostly it's happening after 0.5-2 seconds after start of MainActifity.
On Firebase Crashlytics I am getting thousands of crash events, saying `"This crash event happened in the first second of the user's session."`


OS (determined from Firebaes): All supported Android versions, from 8 to 13
Version of the Library used: 1.1.6

I don't know what's happening there, maybe it's some kind of race condition - library trying to upack notification before NotificationHub.start() was called?

**Comment by pizerg** [comment]
@Klewerro 
> What is the NotificationDisplayer? I cannot find it anywhere? Also registerApplication and I cannot call it :( Did you used `com.microsoft.azure:notification-hubs-android-sdk-fcm` or non `-fcm` library version?

You can find NotificationDisplayer here in the [repo](https://github.com/Azure/azure-notificationhubs-android/blob/main/notification-hubs-sample-app-java/src/fcm/java/com/example/notification_hubs_sample_app_java/cookbook/NotificationDisplayer.java) just modify it to meet your needs.

To be able to call registerApplication you'll need to use "package com.microsoft.windowsazure.messaging.notificationhubs" as the package name for MyFirebaseReceiver

**Comment by Klewerro** [comment]
Okay, now I see what you meant, I didn't notice the package name.
But, you think is that possible to somehow use original way to trigger `onPushNotificationReceived(context: Context, message: RemoteMessage)` ?
I will try to explain:

Here's my FirebaseService:
```Kotlin
var isHubReady: Boolean = false

class MyFirebaseReceiver constructor(
    private val mHub: NotificationHub = NotificationHub.getInstance()
): FirebaseMessagingService() {

    override fun onCreate() {
        super.onCreate()
        mHub.registerApplication(this.application)
    }

    override fun onMessageReceived(remoteMessage: RemoteMessage) {
        Timber.i("isHubReady: $isHubReady")
        if (isHubReady) {
            super.onMessageReceived(remoteMessage)
        } else {
            Timber.i("Notification receiver is not ready - notification ignored.")
        }
    }

    override fun onNewToken(token: String) {
        super.onNewToken(token)
    }
}
```

Basically, I just added a flag to not receive a notifications when app is killed.
And I would like to receive notifications arrived to above implementation into my activityScoped viewModel implementing `NotificationListener` (there's a lot of logic behind showing notifications/data in views). 

Currently, line `super.onMessageReceived(remoteMessage)` is not calling VM onPushNotificationReceived(context: Context, message: RemoteMessage) function.

What do you think, it's easy to achieve, or do I need to bind service, or even somehow differently?
